"""added bike resource

Revision ID: 546ce2ae0a76
Revises: 0e1c39e8d64c
Create Date: 2024-11-13 12:29:18.067462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546ce2ae0a76'
down_revision = '0e1c39e8d64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
