"""removed rental nullable

Revision ID: dbb018c36baa
Revises: 546ce2ae0a76
Create Date: 2024-11-17 23:57:02.848297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb018c36baa'
down_revision = '546ce2ae0a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        # Allow rental_id to be nullable
        batch_op.alter_column(
            'rental_id',
            existing_type=sa.INTEGER(),
            nullable=True
        )

    # Drop the existing foreign key constraint
    op.drop_constraint('payments_bike_id_fkey', 'payments', type_='foreignkey')

    # Add the new foreign key constraint with ON DELETE CASCADE
    op.create_foreign_key(
        'payments_bike_id_fkey',  # Name of the foreign key
        'payments',              # Source table
        'bikes',                 # Target table
        ['bike_id'],             # Column in source table
        ['id'],                  # Column in target table
        ondelete='CASCADE'       # Add the ON DELETE CASCADE behavior
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        # Revert rental_id to be non-nullable
        batch_op.alter_column(
            'rental_id',
            existing_type=sa.INTEGER(),
            nullable=False
        )

    # Drop the foreign key constraint with ON DELETE CASCADE
    op.drop_constraint('payments_bike_id_fkey', 'payments', type_='foreignkey')

    # Re-add the original foreign key constraint without ON DELETE CASCADE
    op.create_foreign_key(
        'payments_bike_id_fkey',  # Name of the foreign key
        'payments',              # Source table
        'bikes',                 # Target table
        ['bike_id'],             # Column in source table
        ['id']                   # Column in target table
    )
    # ### end Alembic commands ###